from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol

from rexecop.operation.model import Operation
from rexecop.operation.plan import OperationPlan


class OperationStoragePort(Protocol):
    """Storage port boundary; FileStore remains the default backend."""

    def save_operation(self, operation: Operation) -> None: ...

    def load_operation(self, operation_id: str) -> Operation: ...

    def list_operations(self) -> list[Operation]: ...

    def save_plan(self, plan: OperationPlan) -> None: ...

    def load_plan(self, operation_id: str) -> OperationPlan: ...

    def save_evidence_event(self, operation_id: str, event: dict[str, Any]) -> None: ...

    def list_evidence_events(self, operation_id: str) -> list[dict[str, Any]]: ...

    def save_structured_log_event(self, event: dict[str, Any]) -> None: ...

    def list_structured_log_events(
        self,
        *,
        operation_id: str | None = None,
        correlation_id: str | None = None,
        limit: int = 50,
    ) -> list[dict[str, Any]]: ...


class RuntimeStore(OperationStoragePort, Protocol):
    """Operator runtime store: port methods plus on-disk aux layout under `.rexecop/`."""

    root: Path

    def ensure_layout(self) -> None: ...

    def operation_sclite_dir(self, operation_id: str) -> Path: ...

    def save_receipt_export(self, operation_id: str, export: dict[str, Any]) -> Path: ...

    def load_receipt_export(self, operation_id: str) -> dict[str, Any]: ...

    def save_approval(self, operation_id: str, approval: dict[str, Any]) -> Path: ...

    def load_approval(self, operation_id: str) -> dict[str, Any]: ...

    def acquire_execution_lease(self, *, worker_id: str) -> dict[str, Any]: ...

    def renew_execution_lease(self, lease: dict[str, Any]) -> dict[str, Any]: ...

    def release_execution_lease(self, lease: dict[str, Any]) -> bool: ...

    def validate_execution_lease(self, lease: dict[str, Any]) -> None: ...

    def queue_list_pending(self) -> list[str]: ...

    def queue_position(self, operation_id: str) -> int | None: ...

    def queue_enqueue(self, operation_id: str) -> int: ...

    def queue_remove(self, operation_id: str) -> None: ...

    def queue_discard_pending(self, operation_id: str) -> None: ...

    def queue_claim(self, lease: dict[str, Any]) -> dict[str, Any] | None: ...

    def queue_complete_claim(self, operation_id: str, lease: dict[str, Any]) -> None: ...

    def allocate_execution_attempt_id(self) -> str: ...

    def start_execution_attempt(self, **binding: Any) -> dict[str, Any]: ...

    def finish_execution_attempt(
        self,
        attempt: dict[str, Any],
        *,
        status: str,
        result_digest: str = "",
        error_class: str = "",
    ) -> dict[str, Any]: ...

    def recover_started_attempts(self) -> list[str]: ...

    def has_indeterminate_side_effect(self, operation_id: str) -> bool: ...

    def list_pending_projection_operations(self) -> list[Operation]: ...

    def save_execution_permit(self, permit: dict[str, Any]) -> Path: ...

    def load_execution_permit(self, operation_id: str, step_id: str) -> dict[str, Any]: ...

    def load_execution_permit_for_attempt(
        self,
        operation_id: str,
        attempt_id: str,
    ) -> dict[str, Any]: ...

    def claim_governance_decision_once(
        self,
        *,
        decision_digest: str,
        nonce: str,
        attempt_id: str,
        runtime_instance_id: str,
    ) -> bool: ...
